version: "3.9"

services:
  user-service-db:
    image: postgres:17
    container_name: user-service-db
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: user_service_user
      POSTGRES_PASSWORD: user_service_password
    ports:
      - "5433:5432"
    volumes:
      - user_service_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_service_user -d user_service_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - home-energy-network

  device-service-db:
    image: postgres:17
    container_name: device-service-db
    environment:
      POSTGRES_DB: device_service_db
      POSTGRES_USER: device_service_user
      POSTGRES_PASSWORD: device_service_password
    ports:
      - "5434:5432"
    volumes:
      - device_service_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U device_service_user -d device_service_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - home-energy-network
  kafka:
    image: apache/kafka:4.1.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - home-energy-network
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-energy-tracker
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: "true"
    depends_on:
      - kafka
    networks:
      - home-energy-network
volumes:
  user_service_db_data:
  device_service_db_data:

networks:
  home-energy-network:
    driver: bridge