CREATE TABLE users
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                   VARCHAR(100)     NOT NULL,
    surname                VARCHAR(100),
    email                  VARCHAR(255)     NOT NULL,
    address                TEXT,
    alerting_enabled       BOOLEAN          NOT NULL DEFAULT FALSE,
    energy_alert_threshold DOUBLE PRECISION NOT NULL DEFAULT 0,
    CONSTRAINT uk_users_email UNIQUE (email)
);