CREATE TABLE devices
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255) NOT NULL,
    type     VARCHAR(50),
    location VARCHAR(255),
    user_id  BIGINT       NOT NULL
);

CREATE INDEX idx_devices_user_id ON devices (user_id);