server:
  port: 8085

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: usage-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.znaji.*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

influx:
  url: http://localhost:8086
  token: usage-service-token
  org: home-energy
  bucket: usage-bucket

user-service:
  base-url: http://localhost:8081

app:
  kafka:
    topics:
      energy-reading-ingested: energy.readings.ingested
      user-usage-threshold-exceeded: energy.usage.threshold.exceeded

  anomaly:
    enabled: true
    scan-interval-ms: 60000
    window-minutes: 5

logging:
  level:
    com.znaji.usageservice: DEBUG